## Exploratory Data Analysis (EDA)
#### SIADS Milestone I - MADS
##### The goal of this notebook is to explore our college football datasets, identify outliers, and implement logic to handle missing data

In [2]:
import altair as alt
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

#### Games dataset

In [16]:
data = pd.read_csv('../data/games_manipulated.csv')

<ipython-input-16-3b053516eb2c>:1: DtypeWarning: Columns (7,15) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data/games_manipulated.csv')

In [17]:
data.head()

,Unnamed: 0,index,id,season,week,season_type,start_date,start_time_tbd,completed,neutral_site,conference_game,attendance,venue_id,venue,excitement_index,highlights,notes,main_team,home_game_flag,team_id,opposing_team_id,team_conference,opposing_conference,points_for,points_against,point_differential,team_line_scores,opposing_line_scores,team_pregame_elo,team_postgame_elo,opponent_pregame_elo,opponent_postgame_elo,win_flag,game_that_season
0,0,1,332412579,2013,1,regular,2013-08-29T22:00:00.000Z,NaN,True,False,False,81572.0,3994.0,Williams-Brice Stadium,NaN,NaN,NaN,South Carolina,1,2579,153,SEC,ACC,27.0,10.0,17.0,"[17, 3, 7, 0]","[0, 7, 3, 0]",1759.0,1785.0,1638.0,1612.0,1,1
1,1,324,332572579,2013,3,regular,2013-09-14T23:00:00.000Z,NaN,True,False,True,81371.0,3994.0,Williams-Brice Stadium,NaN,NaN,NaN,South Carolina,1,2579,238,SEC,SEC,35.0,25.0,10.0,"[21, 7, 7, 0]","[0, 10, 0, 15]",1769.0,1777.0,1644.0,1636.0,1,3
2,2,671,332782579,2013,6,regular,2013-10-05T23:30:00.000Z,NaN,True,False,True,82313.0,3994.0,Williams-Brice Stadium,NaN,NaN,NaN,South Carolina,1,2579,96,SEC,SEC,35.0,28.0,7.0,"[14, 10, 3, 8]","[0, 7, 0, 21]",1780.0,1768.0,1353.0,1365.0,1,5
3,3,1011,333062579,2013,10,regular,2013-11-02T16:21:00.000Z,NaN,True,False,True,82111.0,3994.0,Williams-Brice Stadium,NaN,NaN,NaN,South Carolina,1,2579,344,SEC,SEC,34.0,16.0,18.0,"[14, 3, 17, 0]","[7, 3, 0, 6]",1872.0,1890.0,1634.0,1616.0,1,9
4,4,1295,333202579,2013,12,regular,2013-11-17T00:00:00.000Z,NaN,True,False,True,83853.0,3994.0,Williams-Brice Stadium,NaN,NaN,NaN,South Carolina,1,2579,57,SEC,SEC,19.0,14.0,5.0,"[3, 3, 7, 6]","[7, 7, 0, 0]",1890.0,1887.0,1675.0,1678.0,1,10

In [21]:
power_5_conf = ['SEC', 'ACC', 'Big Ten', 'Pac-12', 'Big 12']

power_5_games = data[data['team_conference'].isin(power_5_conf)]

In [23]:
final_game = power_5_games[power_5_games['game_that_season'] == 12]

final_game.isna().sum()

Unnamed: 0                 0
index                      0
id                         0
season                     0
week                       0
season_type                0
start_date                 0
start_time_tbd           442
completed                  0
neutral_site               0
conference_game            0
attendance                 4
venue_id                   0
venue                      0
excitement_index          62
highlights               389
notes                    634
main_team                  0
home_game_flag             0
team_id                    0
opposing_team_id           0
team_conference            0
opposing_conference        0
points_for                 0
points_against             0
point_differential         0
team_line_scores           0
opposing_line_scores       0
team_pregame_elo           1
team_postgame_elo          1
opponent_pregame_elo       1
opponent_postgame_elo      1
win_flag                   0
game_that_season           0
dtype: int64

In [17]:
# Display basic information about the dataset
pd.set_option("display.float_format", lambda x: "{:.2f}".format(x))
data.describe().T.round(1)

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,42537.00,21268.00,12279.50,0.00,10634.00,21268.00,31902.00,42536.00
index,42537.00,1135.90,895.00,0.00,436.00,959.00,1495.00,3656.00
id,42537.00,396298632.20,17577824.20,332410006.00,400869640.00,401128649.00,401431833.00,401618179.00
season,42537.00,2019.00,3.40,2013.00,2016.00,2019.00,2022.00,2023.00
week,42537.00,6.80,3.90,1.00,3.00,7.00,10.00,20.00
attendance,18401.00,40202.50,26914.20,0.00,18707.00,34014.00,56262.00,156990.00
venue_id,42272.00,4110.70,1139.90,36.00,3699.00,3841.00,4133.00,7555.00
excitement_index,19060.00,4.30,2.60,0.00,2.30,4.10,6.40,21.50
home_game_flag,42537.00,0.50,0.50,0.00,0.00,1.00,1.00,1.00
team_id,42537.00,2521.70,11459.50,2.00,194.00,2029.00,2458.00,127991.00
opposing_team_id,42537.00,2631.30,11993.80,2.00,195.00,2032.00,2458.00,127991.00
points_for,42508.00,27.50,15.30,0.00,16.00,27.00,38.00,98.00
points_against,42508.00,27.30,15.20,0.00,16.00,27.00,38.00,98.00
point_differential,42508.00,0.20,24.30,-98.00,-16.00,1.00,16.00,98.00
team_pregame_elo,16623.00,1517.30,249.80,528.00,1347.00,1519.00,1678.00,2415.00
team_postgame_elo,16597.00,1517.60,257.10,675.00,1342.00,1520.00,1685.00,2400.00
opponent_pregame_elo,16625.00,1515.90,250.30,528.00,1345.00,1518.00,1677.00,2415.00
opponent_postgame_elo,16599.00,1516.00,257.60,675.00,1340.00,1519.00,1684.00,2400.00
win_flag,42537.00,0.50,0.50,0.00,0.00,1.00,1.00,1.00
game_that_season,42537.00,6.30,3.50,1.00,3.00,6.00,9.00,16.00

In [29]:
# Identify missing values
missing_values = data.isnull().sum()
#print("\n % of Values Missing:")
missing_vals = pd.DataFrame(missing_values / len(data)).reset_index()\
                                                       .rename({'index': 'column', 0: '% Missing'}, axis = 1)\
                                                       .sort_values(by = '% Missing', ascending = False)

alt.Chart(missing_vals).mark_bar().encode(
    x = alt.X('% Missing'),
    y = alt.Y('column', sort = '-x'))\
.properties(title = '% of Values Missing by Column')

alt.Chart(...)

#### Individual Recruiting Dataset

In [3]:
data = pd.read_csv('../data/recruits.csv')

# Identify missing values
missing_values = data.isnull().sum()
#print("\n % of Values Missing:")
missing_vals = pd.DataFrame(missing_values / len(data)).reset_index()\
                                                       .rename({'index': 'column', 0: '% Missing'}, axis = 1)\
                                                       .sort_values(by = '% Missing', ascending = False)

alt.Chart(missing_vals).mark_bar().encode(
    x = alt.X('% Missing'),
    y = alt.Y('column', sort = '-x'))\
.properties(title = 'Recruiting Dataset: % of Values Missing by Column')

alt.Chart(...)

In [4]:
data['committed_hasdata_flag'] = np.where(data['committed_to'].isna(), 0, 1)

In [5]:
data.groupby(by = 'year').agg({'committed_hasdata_flag': 'mean'})

      committed_hasdata_flag
year
2013                0.795188
2014                0.791223
2015                0.845344
2016                0.808784
2017                0.775637
2018                0.789367
2019                0.747179
2020                0.745298
2021                0.915601
2022                0.926711
2023                0.945267

In [6]:
a = data.groupby(by = 'year').agg({'committed_hasdata_flag': 'mean'}).reset_index()

alt.Chart(a).mark_line().encode(
    x = 'year:O',
    y = alt.Y('committed_hasdata_flag', title = '% of Records with Committment Data'))\
.properties(height = 300, width = 400, title = '% of Recruits with Committment by Year')

alt.Chart(...)

In [7]:
data['rating_rounded'] = data['rating'].round(2)
scatter = data.groupby(by = ['year', 'rating_rounded']).agg({'committed_hasdata_flag': 'mean'}).reset_index()

alt.Chart(scatter).mark_circle().encode(
    x = alt.X('rating_rounded', scale=alt.Scale(domain=[.5, 1.0]), title = 'Recruiting Rating'), 
    y = alt.Y('committed_hasdata_flag', title = '% of Players With Committment Data')).facet(
    facet = 'year', columns = 4)

alt.FacetChart(...)

In [9]:
no_committed = data[data['committed_hasdata_flag'] == 0]

no_committed.sort_values(by = 'rating', ascending = False).head()

,Unnamed: 0,index,id,athlete_id,recruit_type,year,ranking,name,school,committed_to,position,height,weight,stars,rating,city,state_province,country,latitude,longitude,committed_hasdata_flag,rating_rounded
31786,31786,2,71460,NaN,HighSchool,2021,3.0,J.T. Tuimoloau,Eastside Catholic,NaN,SDE,76.0,277.0,5,0.9990,Sammamish,WA,USA,47.608844,-122.042307,0,1.00
27493,27493,16,61584,NaN,HighSchool,2020,16.0,Zachary Evans,North Shore,NaN,RB,71.0,200.0,5,0.9925,Houston,TX,USA,29.758938,-95.367697,0,0.99
36813,36813,27,92330,NaN,HighSchool,2023,26.0,Samuel M'Pemba,IMG Academy,NaN,ATH,76.0,230.0,5,0.9864,Saint Louis,MO,USA,38.626418,-90.199838,0,0.99
36815,36815,29,92356,NaN,HighSchool,2023,26.0,Jaquavious Russaw,Carver,NaN,EDGE,74.0,230.0,5,0.9859,Troy,AL,USA,31.808768,-85.969951,0,0.99
36849,36849,63,93081,NaN,HighSchool,2023,55.0,DeAndre Moore Jr.,Los Alamitos,NaN,ATH,72.0,185.0,4,0.9760,Los Alamitos,CA,USA,33.803886,-118.077243,0,0.98

#### Team Talent Composite Ratings

In [10]:
data = pd.read_csv('../data/team_talent.csv')

data.head()

   year         school  talent
0  2015        Alabama  981.90
1  2015            USC  926.71
2  2015     Ohio State  907.32
3  2015  Florida State  889.92
4  2015            LSU  889.37

In [11]:
# No Missing values

data.isna().sum()

year      0
school    0
talent    0
dtype: int64

#### Draft dataset

In [13]:
data = pd.read_csv('../data/draft.csv')

data.head()

,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,St,wAV,DrAV,G,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,TD.1,Rec,Yds.2,TD.2,Solo,Int.1,Sk,College/Univ,Unnamed: 28_level_1,draft_year
0,0,1,1,KAN,Eric Fisher,T,22,2021,0,2,8,62,56,132,0,0,0,0,0,0,0,0,1,-3,1,NaN,NaN,NaN,Central Michigan,NaN,2013
1,1,1,2,JAX,Luke Joeckel,T,21,2017,0,0,3,21,16,50,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,Texas A&M,College Stats,2013
2,2,1,3,MIA,Dion Jordan,DE,23,2020,0,0,0,9,3,63,0,0,0,0,0,0,0,0,0,0,0,82,NaN,13.5,Oregon,College Stats,2013
3,3,1,4,PHI,Lane Johnson,T,23,2023,2,5,9,79,79,143,0,0,0,0,0,0,0,0,1,5,1,NaN,NaN,NaN,Oklahoma,College Stats,2013
4,4,1,5,DET,Ezekiel Ansah,DE,24,2020,0,1,5,39,37,93,0,0,0,0,0,0,0,0,0,0,0,174,NaN,50.5,BYU,College Stats,2013

In [15]:
data.shape

(2883, 31)

In [14]:
# Important fields are populated

data.isna().sum()

Unnamed: 0                0
Rnd                       0
Pick                      0
Tm                        0
Player                    0
Pos                       0
Age                       4
To                      214
AP1                       0
PB                        0
St                        0
wAV                     214
DrAV                    361
G                       214
Cmp                     214
Att                     214
Yds                     214
TD                      214
Int                     214
Att.1                   214
Yds.1                   214
TD.1                    214
Rec                     214
Yds.2                   214
TD.2                    214
Solo                    953
Int.1                  2269
Sk                     2018
College/Univ              2
Unnamed: 28_level_1     309
draft_year                0
dtype: int64

#### Team attribute dataset

In [24]:
data = pd.read_csv('../data/teams.csv')

data.head()

,Unnamed: 0,id,school,conference,division,color,logos
0,0,2005,Air Force,Mountain West,Mountain,#004a7b,['http://a.espncdn.com/i/teamlogos/ncaa/500/20...
1,1,2006,Akron,Mid-American,East,#00285e,['http://a.espncdn.com/i/teamlogos/ncaa/500/20...
2,2,333,Alabama,SEC,West,#690014,['http://a.espncdn.com/i/teamlogos/ncaa/500/33...
3,3,2026,Appalachian State,Sun Belt,East,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/20...
4,4,12,Arizona,Pac-12,NaN,#002449,['http://a.espncdn.com/i/teamlogos/ncaa/500/12...

In [25]:
data.isna().sum()

Unnamed: 0     0
id             0
school         0
conference     0
division      53
color          0
logos          0
dtype: int64

In [26]:
data = pd.read_csv('../data/roster.csv')

data.head()

,Unnamed: 0,id,first_name,last_name,team,height,weight,jersey,year,position,home_city,home_state,home_country,home_latitude,home_longitude,home_county_fips,recruit_ids
0,0,13223,Justin,Johnson,Fresno State,73.0,201.0,25.0,2013,DB,Gardena,CA,USA,33.896359,-118.305304,6037.0,[23334]
1,1,100009,Johnny,Jackson,Arizona,NaN,NaN,NaN,2013,WR,San Diego,CA,USA,32.717421,-117.162771,6073.0,[]
2,2,106739,Eric,Thomas,Troy,73.0,NaN,3.0,2013,WR,Shreveport,LA,USA,32.522183,-93.765194,22017.0,[]
3,3,109907,Jon,Lee,Air Force,70.0,NaN,24.0,2013,RB,Bethlehem,GA,USA,34.902030,-84.077412,13291.0,[]
4,4,114698,Jeff,Perry,Central Michigan,74.0,225.0,32.0,2013,LB,Morris,IL,USA,41.357381,-88.421565,17063.0,[27724]

In [28]:
# % missing values

data.isna().sum() / len(data)

Unnamed: 0          0.000000
id                  0.000000
first_name          0.000296
last_name           0.000268
team                0.000000
height              0.056545
weight              0.156623
jersey              0.067661
year                0.000000
position            0.036032
home_city           0.059447
home_state          0.065173
home_country        0.058990
home_latitude       0.080390
home_longitude      0.080390
home_county_fips    0.080853
recruit_ids         0.000000
dtype: float64